Get_Labels:
  runs-on: ubuntu-latest
  outputs:
    labels: ${{ steps.fetch-labels.outputs.labels }}
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch Labels
      id: fetch-labels
      uses: ./actions/labelsworkflow/labelsaddition
      with:
        token: ${{ secrets.API_KEY }} # Use the API_KEY secret
